//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace CapaDatos
{
    [Serializable]
    internal class UnintentionalCodeFirstException : Exception
    {
        public UnintentionalCodeFirstException()
        {
        }

        public UnintentionalCodeFirstException(string message) : base(message)
        {
        }

        public UnintentionalCodeFirstException(string message, Exception innerException) : base(message, innerException)
        {
        }

        protected UnintentionalCodeFirstException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}