//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class salidas
    {
        public int id { get; set; }
        public string empleado { get; set; }
        public string tiposalida { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fechasalida { get; set; }
    }
}
